name: Deploy to Server

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: 157.10.73.52
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        script: |
          cd /var/csv/plp_attendance_api
          # Run the deployment script
          if [ -f "deploy.sh" ]; then
            ./deploy.sh
          else
            # Fallback to manual commands
            git pull origin main
            if [ -d "backend" ]; then
              cd backend
              npm install
              npm run migrate || true
              pm2 restart plp-api || echo "PM2 not configured"
            fi
          fi
